-- COVESTING BOT DATABASE EXPORT
-- Date: 31/12/2025 18:39:41
-- Generated by Database Manager


-- Structure de la table users
undefined

-- Données de la table users (1 lignes)
INSERT INTO users (user_id, username, first_name, last_name, plan, plans, main_balance, trading_balance, referral_balance, referral_earnings, deposited, referrer, referrals, valid_referrals, wallet, last_claim, last_withdraw, last_daily_withdrawal, withdrawal_count_today, free_plan_activated, free_plan_expiry, free_plan_requirements_met, withdrawal_pending, withdrawal_status, created_at, waitlist_position, waitlist_joined_at, waitlist_access_granted, access_code_used, referral_code, total_withdrawn, total_deposited_usdt, total_withdrawn_usdt, notification_settings, last_notification_sent, last_investment_notification, state, state_data, total_trading_earnings, total_referral_earnings, lifetime_referral_earnings, lifetime_trading_earnings) VALUES ('5798607712', 'user5798607712', NULL, NULL, NULL, '[]', '0', '0', '0', '0', '0', NULL, 0, 0, NULL, '0', '0', NULL, 0, false, '0', false, '0', 'none', '"2025-12-31T16:16:40.246Z"', NULL, NULL, false, NULL, '2NWCAC', '0', '0', '0', '{"plan_expiry":true,"trading_updates":true,"referral_updates":true,"investment_reminders":true}', NULL, NULL, 'idle', '{}', '0', '0', '0', '0');


-- Structure de la table withdrawals
undefined


-- Structure de la table transactions
undefined


-- Structure de la table payments
undefined


-- Structure de la table referral_earnings
undefined


-- Structure de la table fee_logs
undefined


-- Structure de la table valid_referrals
undefined


-- Structure de la table deposits
undefined


-- Structure de la table user_states
undefined

